version: "3.9"

services:
  redis:
    image: redis:7.0.4-alpine3.16
    restart: always
    # ports:
    #   - "6379:6379"
    # volumes:
    #   - ./redis:/data

  backend:
    image: api:latest
    restart: always
    ports:
      - "8000:8000" # With express js this can be solved, petitions to same server and from there to the api

  frontend:
    image: ui:latest
    restart: always
    ports:
      - "3000:3000"
